config/routes.rb
Rails.application.routes.draw do
  resources :charts
  resources :speeches do
    collection do 
      get :edit_multiple
      put :update_multiple
    end
  end
  resources :members do
    collection do 
      get :edit_multiple
      put :update_multiple
    end
  end
  root :to => 'members#edit_multiple'

end

app/models/chart.rb
class Chart < ActiveRecord::Base
	has_many :speeches
	belongs_to :member

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]
  before_action :dictionaries

  # GET /charts
  # GET /charts.json
  def index
    if params[:clubname].present?
      @charts = Chart.joins(:member).where("club like ?", "%#{params[:clubname]}%").order("progress": :desc, "lastUpdate": :desc)
    else
      @charts = Chart.all.order("progress": :desc, "lastUpdate": :desc)
    end

    if params[:clubname].present?
      @members = Member.where("club like ?", "%#{params[:clubname]}%")
    else
      @members = Member.all
    end
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
    @members = Member.all
    @speeches = Speech.all
    @charts = Chart.all
    render :layout => nil
  end

  # GET /charts/new
  def new
    @member = Member.find(params[:member_id])
    @chart = Member.find(params[:member_id]).charts.new
    #@chart = Chart.new
  end

  # GET /charts/1/edit
  def edit
  end

  # POST /charts
  # POST /charts.json
  def create
    @chart = Member.find(params[:member_id]).charts.new(chart_params)
    case @chart.name
    when "CC"
      10.times do |i|
        newspeech = @chart.speeches.new
        newspeech.manual = "COMPETENT COMMUNICATION"
        newspeech.project = @ccProjects[i]
        i = i+1
      end
    when "ACB"
      11.times do |i|
        newspeech = @chart.speeches.new
        if i == 10
          newspeech.project = "Complete CC"
        else
          newspeech.manual = "CHOOSE AN ADVANCED MANUAL"
        end
        i = i+1
      end
    when "ACS"
      13.times do |i|
        newspeech = @chart.speeches.new
        if i == 12
          newspeech.project = "Complete ACB"
        elsif i == 10 || 11 
          newspeech.manual = "CHOOSE AN EDUCATIONAL MANUAL"
        else
          newspeech.manual = "CHOOSE AN ADVANCED MANUAL"
        end
        i = i+1
      end
    when "ACG"
      13.times do |i|
        newspeech = @chart.speeches.new
        if i == 11
          newspeech.project = "Mentor a Member"
        elsif i == 12
          newspeech.project = "Complete ACS"
        else
          newspeech.manual = "CHOOSE AN ADVANCED MANUAL"
        end
        i = i+1
      end
    when "CL"
      @clProjects.each do |project, titles|
        titles.each do |title|
          newspeech = @chart.speeches.new
          newspeech.manual = "COMPETENT LEADERSHIP"
          newspeech.project = project
          newspeech.title = title
        end
      end
    when "ALB"
      5.times do |i|
        newspeech = @chart.speeches.new
        case i
        when 2
          newspeech.project = "Club officer for 6 months"
        when 3
          newspeech.project = "Participate in DCP plan meeting"
        when 4
          newspeech.project = "Attend officer training"
        when 5
          newspeech.project = "Complete CC"
        when 6
          newspeech.project = "Complete CL"
        else
          newspeech.manual = "CHOOSE AN EDUCATIONAL MANUAL"
        end
        i = i+1
      end
    when "ALS"
      5.times do |i|
        newspeech = @chart.speeches.new
        case i
        when 0
          newspeech.manual = "HIGH PERFORMANCE LEADERSHIP"
          newspeech.project = "(1) Sharing Your Vision (5-6 min)"
        when 1
          newspeech.manual = "HIGH PERFORMANCE LEADERSHIP"
          newspeech.project = "(2) Presenting the Results (5-7 min)"
        when 2
          newspeech.project = "District officer for 1 year"
        when 3
          newspeech.project = "Sponsor or coach a club"
        when 4
          newspeech.project = "Achieve ALB"
        end
        i = i+1
      end
    end

    respond_to do |format|
      if @chart.save
        format.html { redirect_to edit_multiple_members_path, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /charts/1
  # PATCH/PUT /charts/1.json
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to edit_multiple_members_path, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.json
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_multiple
    @chart = Chart.find(params[:chart_id])
    @speeches = @chart.speeches
  end

  def update_multiple
    @speeches = Speech.update(params[:speeches].keys, params[:speeches].values)
    @chart = Chart.find(params[:chart_id])
    if @speeches.empty?
    redirect_to speeches_url
      else
       render "edit_multiple"
    end
  end

  private
    def dictionaries
      @ccProjects = ["(1) The Ice Breaker (4-6 min)",
                    "(2) Organize Your Speech (5-7 min)",
                    "(3) Get to the Point (5-7 min)",
                    "(4) How to Say It (5-7 min)",
                    "(5) Your Body Speaks (5-7 min)",
                    "(6) Vocal Variety (5-7 min)",
                    "(7) Research Your Topic (5-7 min)",
                    "(8) Get Comfortable with Visual Aids (5-7 min)",
                    "(9) Persuade with Power (5-7 min)",
                    "(10) Inspire Your Audience (8-10 min)"]
      @clProjects = {"(1) Listening" => ["Speech Evaluator",
                                      "Table Topics Speaker",
                                      "Ah Counter",
                                      "Grammarian"],
                   "(2) Critical Thinking" => ["Speech Evaluator",
                                              "Grammarian",
                                               "General Evaluator"],
                   "(3) Giving Feedback" => ["Speech Evaluator",
                                              "Grammarian",
                                              "General Evaluator"],
                   "(4) Time Management" => ["Timer",
                                              "Toastmaster",
                                              "Speaker",
                                              "Topicsmaster",
                                              "Grammarian"],
                   "(5) Planning and Implementation" => ["Speaker",
                                                          "General Evaluator",
                                                          "Toastmaster",
                                                          "Topicsmaster"],
                   "(6) Organization and Delegation" => ["Help Organize a Club Speech Contest",
                                                          "Help Organize a Club Special Event",
                                                          "Help Organize a Club Membership Campaign or Contest",
                                                          "Help Organize a Club PR Campaign",
                                                          "Help Produce a Club Newsletter",
                                                          "Assist the Club's Webmaster"],
                   "(7) Facilitation" => ["Toastmaster",
                                          "General Evaluator",
                                          "Topicsmaster",
                                          "Befriend a Guest"],
                   "(8) Motivation" => ["Membership Campaign or Contest Chair",
                                        "PR Campaign Chair",
                                        "Toastmaster",
                                        "Speech Evaluator",
                                        "General Evaluator"],
                   "(9) Mentoring" => ["Mentor for a New Member",
                                        "Mentor for an Existing Member",
                                        "HPL Guidance Committee Member"],
                   "(10) Team Building" => ["Toastmaster",
                                            "General Evaluator",
                                            "Membership Campaign Chair",
                                            "Club PR Campaign Chair",
                                            "Club Speech Contest Chair",
                                            "Club Special Event Chair",
                                            "Club Newsletter Editor",
                                            "Club Webmaster"]
                  }
      @advancedManuals = ["COMMUNICATING ON TELEVISION",
                "COMMUNICATING ON VIDEO",
                "FACILITATING DISCUSSION",
                "HUMOROUSLY SPEAKING",
                "INTERPERSONAL COMMUNICATIONS",
                "INTERPRETIVE READING",
                "PERSUASIVE SPEAKING",
                "PUBLIC RELATIONS",
                "SPEAKING TO INFORM",
                "SPECIAL OCCASION SPEECHES",
                "SPECIALTY SPEECHES",
                "SPEECHES BY MANAGEMENT",
                "STORYTELLING",
                "TECHNICAL PRESENTATIONS",
                "THE DISCUSSION LEADER",
                "THE ENTERTAINING SPEAKER",
                "THE PROFESSIONAL SALESPERSON",
                "THE PROFESSIONAL SPEAKER"]
      @educationManuals = ["EDUCATIONAL BETTER SPEAKER SERIES",
                "EDUCATIONAL LEADERSHIP EXCELLENCE SERIES",
                "EDUCATIONAL SUCCESSFUL CLUB SERIES"]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
      @chart.progress ||= 0
    end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= simple_form_for(@chart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :collection => %w[CC ACB ACS ACG CL ALB ALS] %>
    <%= hidden_field_tag(:member_id, @chart.member_id) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/charts/_rows.html.erb
<tr>
  <td><%= chart.name %></td>
  <td><%= Member.find(chart.member_id).name %></td>
  <td>
    <div class="progress">
      <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"
      aria-valuenow="<%= chart.progress %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= chart.progress %>%">
        <% unless chart.progress == 0 %>
          <%= chart.progress %>%
        <% end %>
      </div>
    </div>
  </td>
  <td><%= chart.lastUpdate %></td>
  <td>
  <%= form_tag edit_multiple_speeches_path, method: :get do %>
    <%= hidden_field_tag(:chart_id, chart.id) %>
    <%= submit_tag "Edit" %>
  <% end %>
  </td>
  <td><%= link_to 'Delete', chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/charts/_thead.html.erb
<thead>
  <tr>
    <th>Award</th>
    <th>Member</th>
    <th>Progress</th>
    <th>Last Update</th>
    <th colspan="2"></th>
  </tr>
</thead>

app/views/charts/edit.html.erb
<h1>Editing Tracker</h1>

<%= render 'form' %>

<%= form_tag edit_multiple_speeches_path, method: :get do %>
	<%= hidden_field_tag(:chart_id, c.id) %>
<%= submit_tag "Edit Progress", class: "btn btn-primary" %>

app/views/charts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Award Progress</h1>

<h3>Getting Close</h3>
<% if @charts.where.not("progress": 100).maximum("progress") < 75 %>
  <p>No members are close to getting an award.</p>
<% else %>
  <table class="table table-hover">
    <%= render 'thead' %>
    <tbody>
      <% @charts.each do |chart| %>
        <% if chart.try(:progress).blank? %>
            <p>Bust!</p>
        <% elsif (chart.progress >= 75) && (chart.progress < 100)  %>
            <%= render 'rows', :chart => chart %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

<h3>In Progress</h3>
<table class="table table-hover">
  <%= render 'thead' %>
  <tbody>
    <% @charts.each do |chart| %>
      <% if chart.try(:progress).blank? %>
            <p>Bust!</p>
        <% elsif chart.progress < 75  %>
        <%= render 'rows', :chart => chart %>
      <% end %>
    <% end %>
  </tbody>
</table>

<% if @charts.maximum("progress") == 100 %>
  <h3>Recently Completed</h3>
  <table class="table table-hover">
    <%= render 'thead' %>
    <tbody>
      <% @charts.each do |chart| %>
        <% if chart.progress == 100  %>
          <%= render 'rows', :chart => chart %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/charts/new.html.erb
<h1>New Tracker for <%= @member.name %></h1>

<%= render 'form' %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<h2>
  <%= @members.find(@chart.member_id).name %>'s <%= @chart.name %> Progess
</h2>
</p>

<p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Manual</th>
        <th scope="col">Project</th>
        <th scope="col">Title</th>
        <th scope="col">Date</th>
        <th scope="col">Club</th>
        <th scope="col">Comment</th>
      </tr>
    </thead>
    <tbody>
      <% if @chart.speeches.nil? %>
        <tr>
          <td>No Speeches</td>
        </tr>
      <% else %>
        <% @chart.speeches.each do |s| %>
        	<tr>
        		<td><%= s.manual %></td>
        		<td><%= s.project %></td>
        		<td><%= s.title %></td>
        		<td><%= s.date %></td>
        		<td><%= s.club %></td>
        		<td><%= s.comment %></td>
        	</tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</p>

<%= link_to 'Edit', edit_chart_path(@chart) %>