config/routes.rb
Rails.application.routes.draw do
  resources :charts
  resources :speeches do
    collection do 
      get :edit_multiple
      put :update_multiple
    end
  end
  resources :members do
    collection do 
      get :edit_multiple
      put :update_multiple
    end
  end
  root :to => 'members#edit_multiple'

end

app/models/speech.rb
class Speech < ActiveRecord::Base
	belongs_to :chart
end

app/controllers/speeches_controller.rb
class SpeechesController < ApplicationController
  before_action :set_speech, only: [:show, :edit, :update, :destroy]
  before_action :dictionaries
  after_action :update_chart, only: [:edit_multiple, :update_multiple]

  # GET /speeches
  # GET /speeches.json
  def index
    @speeches = Speech.all
  end

  # GET /speeches/1
  # GET /speeches/1.json
  def show
  end

  # GET /speeches/new
  def new
    @speech = Speech.new
  end

  # GET /speeches/1/edit
  def edit
  end

  # POST /speeches
  # POST /speeches.json
  def create
    @speech = Speech.new(speech_params)


    respond_to do |format|
      if @speech.save
        format.html { redirect_to @speech, notice: 'Speech was successfully created.' }
        format.json { render :show, status: :created, location: @speech }
      else
        format.html { render :new }
        format.json { render json: @speech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speeches/1
  # PATCH/PUT /speeches/1.json
  def update
    respond_to do |format|
      if @speech.update(speech_params)
        format.html { redirect_to @speech, notice: 'Speech was successfully updated.' }
        format.json { render :show, status: :ok, location: @speech }
      else
        format.html { render :edit }
        format.json { render json: @speech.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speeches/1
  # DELETE /speeches/1.json
  def destroy
    @speech.destroy
    respond_to do |format|
      format.html { redirect_to speeches_url, notice: 'Speech was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_multiple
    @chart = Chart.find(params[:chart_id])
    @speeches = @chart.speeches
    markAsDone()

  end

  def update_multiple
    @chart = Chart.find(params[:chart_id])
    @speeches = Speech.update(params[:speeches].keys, params[:speeches].values)
    markAsDone()
    #@speeches = Speech.update(params[:speeches].keys, params[:speeches].values)
    if @speeches.empty?
    redirect_to speeches_url
      else
       render "edit_multiple"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speech
      @speech = Speech.find(params[:id])
    end
    def checkMe(start,duration,min)
      done = 0
      finish = start + duration
      duration.times do
        done = done + (@speeches[start]["date"].nil? ? 0 : 1)
        #done = done.to_s + @speeches[start]["date"].to_s #troubleshooting
        start = start + 1
      end
      return (done >= min)
      #return done #troubleshooting
    end

    def markAsDone()
      i=1
      #params[:speeches].each do |id v|
      #  s = Speech.find(v)
      @speeches.each do |s|
        if s["date"].present?
          s["done"] = true
        elsif @chart.name.include?("CL")
          check = case s.project
          when "(1) Listening"
            checkMe(0,4,3)
          when "(2) Critical Thinking"
            checkMe(4,3,2)
          #when "(3) Giving Feedback"
          #  check(7,3,3)
          when "(4) Time Management"
            (checkMe(10,1,1) && checkMe(11,4,1))
          when "(5) Planning and Implementation"
            checkMe(15,4,3)
          when "(6) Organization and Delegation"
            checkMe(19,6,1)
          when "(7) Facilitation"
            checkMe(25,4,2)
          when "(8) Motivation"   
            (checkMe(29,2,1) && checkMe(31,3,2))
          when "(9) Mentoring"  
            checkMe(34,3,1)          
          when "(10) Team Building" 
            (checkMe(37,2,2) || checkMe(39,6,1))
          end
          if check == true
              s["done"] = true
          #else #troubleshooting
          #    s["title"] = check #troubleshooting
          end
        else
          s["done"] = false
        end
        if @chart.name.include?("AC")
          case i
          when 1
            @manual1 = s["manual"]
          when 2,3,4,5
            s["manual"] = @manual1
          when 6
            @manual2 = s["manual"]
          when 7,8,9,10
            s["manual"] = @manual2
          end
        end
        s.save
        i=i+1
      end
    end

    def update_chart()
      total = 0
      done = 0
      @chart.speeches.each do |speech|
        total = total+1
        done = done+1 if speech.done == true
      end
      progress = (100*done.to_f/total.to_f).round
      @chart.update_attribute(:progress, progress)

      inProgress = nil
      date = Date.parse("1/1/0000")
      @chart.speeches.each do |speech|
        if speech.done.nil?
          inProgress = true
        elsif speech.date.present? && (speech.date > date)
          date = speech.date
        end
      end
      @chart.update_attribute(:lastUpdate, date)

      if inProgress.nil?
        done = date
      else
        done = nil
      end
      @chart.update_attribute(:done, done)
    end

    def dictionaries 
     @advancedManuals = ["COMMUNICATING ON TELEVISION",
                  "COMMUNICATING ON VIDEO",
                  "FACILITATING DISCUSSION",
                  "HUMOROUSLY SPEAKING",
                  "INTERPERSONAL COMMUNICATIONS",
                  "INTERPRETIVE READING",
                  "PERSUASIVE SPEAKING",
                  "PUBLIC RELATIONS",
                  "SPEAKING TO INFORM",
                  "SPECIAL OCCASION SPEECHES",
                  "SPECIALTY SPEECHES",
                  "SPEECHES BY MANAGEMENT",
                  "STORYTELLING",
                  "TECHNICAL PRESENTATIONS",
                  "THE DISCUSSION LEADER",
                  "THE ENTERTAINING SPEAKER",
                  "THE PROFESSIONAL SALESPERSON",
                  "THE PROFESSIONAL SPEAKER"]
      @educationManuals = ["EDUCATIONAL BETTER SPEAKER SERIES",
                  "EDUCATIONAL LEADERSHIP EXCELLENCE SERIES",
                  "EDUCATIONAL SUCCESSFUL CLUB SERIES"]
      @projects = {"COMMUNICATING ON TELEVISION" => ["(1) Straight Talk (3 min)",
                    "(2) The Talk Show (10 min)",
                    "(3) When You're the Host (10 min)",
                    "(4) The Press Conference (4-6 min presentation; 8-10 min Q&amp;A)",
                    "(5) Training on Television (5-7 min; 5-7 min video tape playback)"],
                    "COMMUNICATING ON VIDEO" => ["(1) The Straight Talk (3 min)",
                    "(2) The Interview Show (5-7 min)",
                    "(3) When You're the Host (5-7 min)",
                    "(4) The Press Conference (3-5 min; 2-3 min for Q&amp;A)",
                    "(5) Instructing on the Internet (5-7 min; 5-7 min for video playback)"],
                    "FACILITATING DISCUSSION" => ["(1) The Panel Moderator (28-30 min or optional 22-26 min)",
                    "(2) The Brainstorming Session (31-33 min or optional 20-22 min)",
                    "(3) The Problem-Solving Discussion (26-31 min or optional 19-23 min)",
                    "(4) Handling Challenging Situations (22-32 min or optional 12-21 min)",
                    "(5) Reaching a Consensus (31-37 min or optional 20-26 min)"],
                    "HUMOROUSLY SPEAKING" => ["(1) Warm Up Your Audience (5-7 min)",
                    "(2) Leave Them with a Smile (5-7 min)",
                    "(3) Make Them Laugh (5-7 min)",
                    "(4) Keep Them Laughing (5-7 min)",
                    "(5) The Humorous Speech (5-7 min)"],
                    "INTERPERSONAL COMMUNICATIONS" => ["(1) Conversing with Ease (10-14 min)",
                    "(2) The Successful Negotiator (10-14 min)",
                    "(3) Diffusing Verbal Criticism (10-14 min)",
                    "(4) The Coach (10-14 min)",
                    "(5) Asserting Yourself Effectively (10-14 min)"],
                    "INTERPRETIVE READING" => ["(1) Read a Story (8-10 min)",
                    "(2) Interpreting Poetry (6-8 min)",
                    "(3) The Monodrama (5-7 min)",
                    "(4) The Play (12-15 min)",
                    "(5) The Oratorical Speech (8-10 min)"],
                    "PERSUASIVE SPEAKING" => ["(1) The Effective Salesperson (3-4 min speech; 3-5 min role play; 2-3 min discussion)",
                    "(2) Conquering the Cold Call (3-4 min speech; 5-7 min role play; 2-3 min discussion)",
                    "(3) The Winning Proposal (5-7 min)",
                    "(4) Addressing the Opposition (7-9 min speech; 2-3 min Q&amp;A)",
                    "(5) The Persuasive Leader (6-8 min)"],
                    "PUBLIC RELATIONS" => ["(1) The Goodwill Speech (5-7 min)",
                    "(2) The Radio Talk Show (3-5 min; 2-3 min Q&amp;A)",
                    "(3) The Persuasive Approach (5-7 min)",
                    "(4) Speaking Under Fire (3-5 min; 2-3 min Q&amp;A)",
                    "(5) The Crisis Management Speech (4-6 min; 3-5 min Q&amp;A)"],
                    "SPEAKING TO INFORM" => ["(1) The Speech to Inform (5-7 min)",
                    "(2) Resources for Informing (5-7 min)",
                    "(3) The Demonstration Talk (5-7 min)",
                    "(4) A Fact-Finding Report (5-7 min; 2-3 min Q&amp;A)",
                    "(5) The Abstract Concept (6-8 min)"],
                    "SPECIAL OCCASION SPEECHES" => ["(1) Mastering the Toast (2-3 min)",
                    "(2) Speaking in Praise (5-7 min)",
                    "(3) The Roast (3-5 min)",
                    "(4) Presenting an Award (3-4 min)",
                    "(5) Accepting an Award (5-7 min)"],
                    "SPECIALTY SPEECHES" => ["(1) Impromptu Speaking (5-7 min)",
                    "(2) Uplift the Spirit (8-10 min)",
                    "(3) Sell a Product (10-12 min)",
                    "(4) Read Out Loud (12-15 min)",
                    "(5) Introduce the Speaker (duration of a club meeting)"],
                    "SPEECHES BY MANAGEMENT" => ["(1) The Briefing (3-5 min; 2-3 min  Q&amp;A)",

app/helpers/speeches_helper.rb
module SpeechesHelper
end

app/views/speeches/_form.html.erb
<%= simple_form_for(@speech) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :manual %>
    <%= f.input :project %>
    <%= f.input :title %>
    <%= f.input :date %>
    <%= f.input :club %>
    <%= f.input :comment %>
    <%= f.input :chart_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/speeches/edit.html.erb
<h1>Editing Speech</h1>

<%= render 'form' %>

<%= link_to 'Show', @speech %> |
<%= link_to 'Back', speeches_path %>

app/views/speeches/edit_multiple.html.erb
<% total = 0 %>
<% done = 0 %>
<% @speeches.each do |speech| %>
	<% total = total+1 %>
	<% if speech.done == true %>
		<% done = done+1 %>
	<% end %>
<% end %>
<% progress = (100*done.to_f/total.to_f).round %>

<h2><%= @chart.member.name %>'s <%= @chart.name %> Progress: <%= progress %>%</h2>

<%= form_tag update_multiple_speeches_path, method: :put do %>
	<table class="table table-hover">
	  <thead>
      <tr>
        <th scope="col">Manual</th>
        <th scope="col">Project</th>
        <th scope="col">Title</th>
        <th scope="col">Date</th>
        <th scope="col">Club</th>
        <th scope="col">Comment</th>
      </tr>
    </thead>
		<tbody>
      <% if @speeches.nil? %>
        <tr>
          <td>No Speeches</td>
        </tr>
      <% else %>
      	<% i=1 %>
        <% @speeches.each do |speech| %>
        	<%= fields_for "speeches[]", speech do |f| %>
						      		<% if speech.errors.any? %>
						        		<div id="error_explanation">
						          		<h2><%= pluralize(speech.errors.count, "error") %> prohibited this speech from being saved:</h2>
						          		<ul>
						          			<% speech.errors.full_messages.each do |msg| %>
						            			<li><%= msg %></li>
						          			<% end %>
						          		</ul>
						        		</div>
						      		<% end %>
		      	<% if speech.done == true %>
		      		<tr class="bg-success">
		      	<% else %>
		      		<tr>
		      	<% end %>
		      		<% if @chart.name.include?("AC") && (i == 1 || i == 6) %>
		      			<td><%= f.select :manual, @advancedManuals %></td>
		      		<% elsif (@chart.name.include?("ACS") && (i == 11 || i == 12)) || (@chart.name.include?("ACG") && (i == 11)) ||	(@chart.name.include?("ALB") && (i == 1 || i == 2)) %>
		      			<td><%= f.select :manual, @educationManuals %></td>		      		
		      		<% else %>
		      			<td><%= f.text_field :manual, :disabled=> "disabled", :size => "40px" %></td>
		      		<% end %>
							<% if (@chart.name.include?("AC") && (i.between?(1,10)) || speech.manual.to_s.include?("EDUCATIONAL")) %>
								<% projectArray = @projects[speech.manual] %>
								<% projectArray ||= [] %>
								<td><%= f.select :project, projectArray, :selected => projectArray[i%5 - 1] %></td>
							<% else %>
								<td><%= f.text_field :project, :disabled => "disabled", :size => "40px" %></td>
							<% end %>
							<% if @chart.name.include?("CL") %>
								<td><%= f.text_field :title, :disabled => "disabled" %></td>
							<% else %>
		      			<td><%= f.text_field :title %></td>
		      		<% end %>
		      		<% if speech.date.nil? && speech.done == true %>
		      			<td>N/A</td>
		      		<% else %>
		      			<td><%= f.date_field :date, max: Date.today %></td>
		      		<% end %>
		      		<td><%= f.select :club, %w(Leadership\ Lambda Other) %></td>
		      		<% if @chart.name.include?("CL") %>
		      			<% unless @notes[i].nil? %>
		      				<td rowspan=<%= @notes[i][0] %>>
		      					<p><%= @notes[i][1] %></p>
		      					<%= f.text_area :comment, :height => "100%" %>
		      				</td>
		      			<% end %>
		      		<% else %>
		      			<td><%= f.text_field :comment %></td>
		      		<% end %>
	        	</tr>
	        <% end %>
	       	<% i = i+1 %>
	      <% end %>
	    <% end %>
	 	</tbody>
	</table>
	<%= hidden_field_tag(:chart_id, @chart.id) %>
  <%= submit_tag "Update", class: "btn btn-primary" %>
<% end %>

app/views/speeches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Speeches</h1>

<table>
  <thead>
    <tr>
      <th>Manual</th>
      <th>Project</th>
      <th>Title</th>
      <th>Date</th>
      <th>Club</th>
      <th>Comment</th>
      <th>Chart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speeches.each do |speech| %>
      <tr>
        <td><%= speech.manual %></td>
        <td><%= speech.project %></td>
        <td><%= speech.title %></td>
        <td><%= speech.date %></td>
        <td><%= speech.club %></td>
        <td><%= speech.comment %></td>
        <td><%= speech.chart_id %></td>
        <td><%= link_to 'Show', speech %></td>
        <td><%= link_to 'Edit', edit_speech_path(speech) %></td>
        <td><%= link_to 'Destroy', speech, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speech', new_speech_path %>

app/views/speeches/new.html.erb
<h1>New Speech</h1>

<%= render 'form' %>

<%= link_to 'Back', speeches_path %>

app/views/speeches/show.html.erb
<%= render 'form' %>