config/routes.rb
Rails.application.routes.draw do
  resources :charts
  resources :speeches do
    collection do 
      get :edit_multiple
      put :update_multiple
    end
  end
  resources :members do
    collection do 
      get :edit_multiple
      put :update_multiple
    end
  end
  root :to => 'members#edit_multiple'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #772432;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Toast Tracker", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% @clubs = ["Leadership Lambda", "Talking Heads of Stuart"] %> 
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Club Members <span class="caret"></span></a>
          <!-- <!% link_to "My Club Members", "#", :class => "dropdown-toggle", "data-toggle" => "dropdown" %> --> 
          <ul class="dropdown-menu">
            <% @clubs.each do |club| %>
              <% @label = "members-" + club.parameterize %>
              <%= form_tag edit_multiple_members_path, id: @label, method: :get do %>
                <%= hidden_field_tag(:clubname, club) %>
              <% end %>
              <%= link_to club, "#", :onclick => "$('##{@label}').submit()", :class => "nav navbar-nav" %>
            <% end %>
          </ul>
        </li>

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Club Awards <span class="caret"></span></a>
        <!-- <!% link_to "My Club Awards", charts_path, :class => "dropdown-toggle", "data-toggle" => "dropdown" %> -->
          <ul class="dropdown-menu">
            <% @clubs.each do |club| %>
              <% @label = "awards-" + club.parameterize %>
              <%= form_tag charts_path, id: @label, method: :get do %>
                <%= hidden_field_tag(:clubname, club) %>
              <% end %>
              <%= link_to club, "#", :onclick => "$('##{@label}').submit()" %>
            <% end %>
          </ul>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toastmasters Education Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>