config/routes.rb
Rails.application.routes.draw do
  resources :charts
  resources :speeches do
    collection do 
      get :edit_multiple
      put :update_multiple
    end
  end
  resources :members do
    collection do 
      get :edit_multiple
      put :update_multiple
    end
  end
  root :to => 'members#edit_multiple'

end

app/models/member.rb
class Member < ActiveRecord::Base
	has_many :charts, :autosave=>true
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to edit_multiple_members_path, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to edit_multiple_members_path, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_multiple
    if params[:clubname].present?
      @members = Member.where("club like ?", "%#{params[:clubname]}%")
    else
      @members = Member.all
    end
  end

  def update_multiple
    @members = Member.update(params[:members].keys, params[:members].values)
    if @members.empty?
    redirect_to members_url
      else
       render "edit_multiple"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :level, :communicationGoal, :leadershipGoal, :club, :award, :clubname)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Level</th>
        <th scope="col">Communication Goal</th>
        <th scope="col">Leadership Goal</th>
        <th scope="col">Club</th>
        <th scope="col">Awards</th>
        <th scope="col" colspan="1"></th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= f.text_field :name %></td>
          <td><%= f.text_field :level %></td>
          <td><%= f.text_field :communicationGoal %></td>
          <td><%= f.text_field :leadershipGoal %></td>
          <td><%= f.text_field :club %></td>
          <td><%= f.text_field :award %></td>
          <td><%= f.submit %></td>
        </tr>
    </tbody>
  </table>
  
<% end %>

app/views/members/edit.html.erb
<%= render 'form' %>

<%= form_tag edit_multiple_members_path, method: :get do %>
  <%= submit_tag "All Members", :class => "btn btn-primary" %>
<% end %>

app/views/members/edit_multiple.html.erb
<%= form_tag update_multiple_members_path, method: :put do %>
<h1><%= params[:clubname] %> Members</h1>
	<table class="table table-hover">
		<thead>
		  <tr>
		    <th scope="col">Name</th>
		    <th scope="col">Education Level</th>
		    <th scope="col">Trackers</th>
		    <th scope="col" style="display:none;">Communication Goal</th>
		    <th scope="col" style="display:none;">Leadership Goal</th>
		    <th scope="col">Club</th>
		    <th scope="col" style="display:none;">Awards</th>
		  </tr>
		</thead>
		<tbody>
 		<% @members.each do |member| %>
 			<%= fields_for "members[]", member do |f| %>
	      <% if member.errors.any? %>
	        <div id="error_explanation">
	          <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>
	          <ul>
	          <% member.errors.full_messages.each do |msg| %>
	            <li><%= msg %></li>
	          <% end %>
	          </ul>
	        </div>
	      <% end %>
	      <% if member.charts[1].nil? %> <!-- Fix this later -->
        	<tr class="bg-warning" >
        <% else %>
        	<tr>
        <% end %>
          <td><%= f.text_field :name %></td>
          <td><%= f.text_field :level %></td>
          <td>
          <% member.charts.each do |c| %>
          	<p>
          		<% label = c.name.to_s + ": " + c.progress.to_s + "%" %>
	          	<%= form_tag edit_multiple_speeches_path, method: :get do %>
			  				<%= hidden_field_tag(:chart_id, c.id) %>
		  					<%= submit_tag label, class: "btn btn-primary", :style => "width:100px;" %>
							<% end %>
          	</p>
          <% end %>
          <p><%= link_to 'New', new_chart_path(member_id: member.id) %></p>
          </td>
          <td style="display:none;" ><%= f.text_field :communicationGoal %></td>
          <td style="display:none;" ><%= f.text_field :leadershipGoal %></td>
          <td><%= f.text_field :club %></td>
          <td style="display:none;" ><%= f.text_field :award %></td>
        </tr>
 			<% end %>
 		<% end %>
 		</tbody>
  </table>
  <%= submit_tag "Update Member Info", class: "btn btn-success" %>
<% end %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Level</th>
      <th scope="col">Communication Goal</th>
      <th scope="col">Leadership Goal</th>
      <th scope="col">Club</th>
      <th scope="col">Awards</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.level %></td>
        <td><%= member.communicationGoal %></td>
        <td><%= member.leadershipGoal %></td>
        <td><%= member.club %></td>
        <td><%= member.award %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

<%= form_tag edit_multiple_members_path, method: :get do %>
  <%= submit_tag "Edit Multiple Members" %>
<% end %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= form_tag edit_multiple_members_path, method: :get do %>
  <%= submit_tag "All Members" %>
<% end %>

app/views/members/show.html.erb
<%= render edit_multiple_members_path %>